export const SET_ALERT = "SET_ALERT";

export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

export const USER_LOADED = "USER_LOADED";

export const AUTH_FAILURE = "AUTH_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";
