export const SET_ALERT = "SET_ALERT";

export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";

export const USER_LOADED = "USER_LOADED";

export const AUTH_FAILURE = "AUTH_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOG_OUT = "LOG_OUT";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const GET_PROFILE_ERROR = "PROFILE_ERROR";

export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";

export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";

export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";

export const ADD_EDUCATION_FAILURE = "ADD_EDUCATION_FAILURE";

export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";

export const ADD_EXPERIENCE_FAILURE = "ADD_EXPERIENCE_FAILURE";

export const USER_DELETED = "USER_DELETED";
